### ISSUE TITLE
No configuration option for Alchemy Validation with Devise. 

### ISSUE THREAD

**Issue by shushugah** [AlchemyCMS/alchemy-devise#51]
There are two simple issues. 

When using devise for example `:email` as authentication key,  the validation for uniqueness of `:login` is still present. There should be an easy way to turn this off. 

When you DO want unique :login attributes, `nil` is currently an acceptable unique value, so `validates_uniqueness_of :login` should also include `validates_presence_of :login` 

In order to solve this, I removed Alchemy Validators (two at the moment) and reinserted one I wanted to keep. The devise validators were untouched. 

```
Alchemy::User.class_eval do
  clear_validators!
    validates_presence_of :alchemy_roles
  devise *Alchemy::User::DEVISE_MODULES += [:registerable]
end
```

A proposed solution would be to add some helper method in user.rb

```
validates_presence_of :login,  if: used_for_authentication?
validates_uniqueness_of :login, if: used_for_authentication?
  def used_for_authentication?
    Devise.authentication_keys.include?(:login)
  end
```

**Comment by tvdeyen** [comment]
Yes. This issue needs to be resolved. Wouldn't it be possible to dynamically add validations for configured authentication key? Something like:

~~~ruby
Devise.authentication_keys.each do |key|
  validate key, {presence: true}, {uniqueness: true}
end
~~~

**Comment by tvdeyen** [comment]
Fun fact: we include the Devise `validatable` module. That adds an email validation. Email should only be required if it's configured. But actually Devise does not check if email is actually used as authentication key.

**Comment by robinboening** [comment]
I like the idea of defining validations on the fly for the `authentication_keys`. 👍 

I also thought this might be a good change in Devise instead.

**Comment by robinboening** [comment]
Beside that there is also this line of code:

`devise *Alchemy::User::DEVISE_MODULES += [:registerable]`

I was wondering why Devise is built like that and does not take the modules from its configuration setup. If Devise would do that, we could just define the needed modules in `initializers/devise.rb` instead of monkey patching our `User` class.

**Comment by robinboening** [comment]
I think I just answered my thoughts myself... its because that way each model can use different modules.

**Comment by robinboening** [comment]
But as a feature suggestion: We could provide a `alchemy/config.yml` that only includes the devise modules and we read from that in the `Alchemy::User` class.

```
# Alchemy::User
DEVISE_MODULES = Alchemy::Config.get(:devise_modules)
```

**Comment by tvdeyen** [comment]
I think we are mixing up things here.

### 1. We want to only validate keys that are configured for Devise. 

I think we can achieve this by using my solution mentioned above.

### 2. Devise module configuration via Alchemy configuration. 

That is a good idea (we had this once the user model was still in the core, remember?), but to achieve that there is more involved, because Alchemy does not support to add something to the config via an plugin. 

We could add a `app/config/alchemy/devise.yml`, but then we need to duplicate all the configuration reading code from the core. 

A solution could be to patch the core so it loads all `app/config/alchemy/*.config.yml` files and merges them together. So we could then have a `app/config/alchemy/devise.config.yml` file and use the configuration code from the core. (We can't just load all `*.yml` files in the `app/config/alchemy` folder, because the `elements.yml` and `page_layouts.yml` files also are in this folder.)

Or: Change the configuration file to `app/config/alchemy.yml` and then load all `app/config/alchemy.*.yml` files into the configuration. This would follow rails conventions, but is a bigger change for existing sites.

WDYT?

**Comment by tvdeyen** [comment]
PR https://github.com/AlchemyCMS/alchemy-devise/pull/59 allows to configure `Alchemy.devise_modules`.
